# Generated by Django 3.0 on 2019-12-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Other', 'Other')], default='Other', help_text='Age', max_length=255),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.FloatField(help_text='Latitude'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.FloatField(help_text='Longitude'),
        ),
    ]
